kind: pipeline
name: default

steps:
- name: build
  image: alpine
  environment:
    USERNAME:
      from_secret: username
  commands:
  - echo "TESTING"

---
kind: secret

external_data:
  username:
    path: secret/my-secret
    name: my-value
